# Cosmos Discord Faucet configuration

verbose        = "yes"

[cosmos]
prefix         = "sei"
denomination   = "usei"

[testnets]
    [testnets.theta]
    node_url = "http://localhost:26657"
    chain_id = "sei-chain"
    faucet_address = "sei1gyvh0weymtt2spl8rw63088s0dvkcdjn87gjfl"
    block_explorer_tx = "https://explorer.sei.prithvidevs.in/sei"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "500"

[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = "faucet_bot"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "86400"
