# Cosmos Discord Faucet configuration

verbose        = "yes"

[cosmos]
prefix         = "sei"
denominations   = ["usei"]

[testnets]
    [testnets.theta]
    node_url = "https://rpc.atlantic-2.seinetwork.io"
    chain_id = "atlantic-2"
    faucet_address = "sei1pvv9lfj4g9kleux43epgej9trnf2tenj0e6dff"
    block_explorer_tx = "https://sei.explorers.guru/transaction/"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "2000"

[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = "faucet_bot"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout = "86400"
